monitor_task:
  description: >
    Determine when a device is connected.
    Find the IP Address of that device.
  expected_output: >
    All devices and their IP address in a table
  agent: monitor


